<x-filament-panels::page>
    <div class="max-w-md mx-auto">
        {{-- Header card with premium gradient and friendly vibe --}}
        <div class="rounded-2xl bg-gradient-to-br from-amber-500 via-orange-500 to-rose-500 p-6 text-white text-center shadow-xl mb-6 relative overflow-hidden">
            {{-- Decorative pattern overlay --}}
            <div class="absolute inset-0 opacity-10 bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-white via-transparent to-transparent"></div>
            
            <div class="relative z-10">
                <div class="text-5xl mb-3 animate-bounce">🔒✨</div>
                <h2 class="text-2xl font-black tracking-tight">Security Check, Super Friend!</h2>
                <p class="text-sm text-white/90 mt-3 leading-relaxed">
                    Our servers refused to let you pass with that autogenerated password. It was too "robot-esque" for their liking. 🤖
                </p>
                <div class="mt-4 px-3 py-1.5 bg-white/20 rounded-full inline-block text-xs font-semibold backdrop-blur-sm">
                    Time to craft your custom secret phrase!
                </div>
            </div>
        </div>

        {{-- Form card --}}
        <div class="rounded-2xl bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 shadow-xl p-6 relative">
            <form wire:submit="save">
                {{ $this->form }}

                <div class="mt-6">
                    <x-filament::button
                        type="submit"
                        size="lg"
                        class="w-full shadow-lg shadow-orange-500/20 hover:shadow-orange-500/35 transition-all duration-300"
                        color="warning"
                    >
                        🚀 Ban the Robot Password & Let Me In!
                    </x-filament::button>
                </div>
            </form>
        </div>

        {{-- Funny disclaimer --}}
        <div class="text-center mt-6 space-y-2">
            <p class="text-xs text-gray-400 dark:text-gray-500 italic">
                "No, 12345678 is not a secure password. Neither is password123. Yes, we will check."
            </p>
            <p class="text-xs font-bold text-amber-600 dark:text-amber-500">
                🔒 You're locked out of the dashboard until this is done! No pressure. 😉
            </p>
        </div>
    </div>
</x-filament-panels::page>
